version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-deps-{{checksum "package.json"}}
          - v1-deps-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{checksum "package.json"}
      - run: npm run lint
      - run: npm test
